### ISSUE TITLE
Running 'ember electron:test' on CI

### ISSUE THREAD

**Issue by davydany** [felixrieseberg/ember-electron#346]
The following is my CI Config on Gitlab-CI. The build is failing with the error `Error: Browser failed to connect within 30s. testem.js not loaded?`. On my local, the tests run fine. What do I need to do different to run Ember Electron's tests on CI? I am assuming that this is an issue anyone will encounter on any CI platform. 

```
stages:
  - test
  - package

cache:
  paths:
  - bower_components/
  - node_modules/

run-tests:
  stage: test
  image: node:7.4.0
  before_script:
    - apt-get update
    - apt-get install -y xvfb libgtk2.0-0 libnotify4 libgconf-2-4 libnss3
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install -g yarn
    - npm install -g bower
    - yarn install
    - bower install --allow-root
  script:
    - echo "Kicking off Tests..."
    - yarn run test

...
```

*The Error Message:*

```
yarn run test 
yarn run v1.5.1
warning You are using Node "7.4.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
$ ember electron:test
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Building and assembling
cleaning up
cleaning up...
Built and assembled Electron project successfully. Stored in "/builds/davydany/citrus-client/tmp/class-tests_dist-AJL7CCIl.tmp".
DEPRECATION: This test-runner.js is deprecated. Please read https://github.com/felixrieseberg/ember-electron/blob/master/docs/faq/test-runner-deprecation.md for more information.
not ok 1 Electron - error
    ---
        message: >
            Error: Browser failed to connect within 30s. testem.js not loaded?
            
        Log: |
            { type: 'error',
              text: 'Error: Browser failed to connect within 30s. testem.js not loaded?' }
    ...

1..1
# tests 1
# pass  0
# skip  0
# fail  1
```
