### ISSUE TITLE
Build failing on Travis CI with a bare project

### ISSUE THREAD

**Issue by LrsNate** [felixrieseberg/ember-electron#79]
Hi,

I'm using ember-cli@2.6.2:

```
> ember -v
ember-cli: 2.6.2
node: 6.2.2
os: darwin x64
```

I created a minimal project by running this:

```
ember init
ember install ember-electron
```

And the build was failing with nslog. Turns out you also need to add a recent version of gcc in your `.travis.yml` file, like so:

```
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
```

Could be worth updating the doc to add that bit of configuration :) (I'll happily make a PR if needed!)
More details on this issue: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
